name: xray-lab

services:
  xray-server:
    image: ghcr.io/xtls/xray-core:${XRAY_VER}
    container_name: xray-server
    restart: unless-stopped
    env_file:
      - .env
      - .env.secrets
    ports:
      - "443:443"
      - "443:443/udp"
    # По умолчанию образ читает confdir /usr/local/etc/xray/ со всеми дефолтными json.
    # Переопределяем команду чтобы читал только наш конфиг.
    command: ["run", "-config", "/usr/local/etc/xray/config.json"]
    volumes:
      - ./configs/server/config.json:/usr/local/etc/xray/config.json:ro
