name: xray-lab

services:
  xray-server:
    image: ghcr.io/xtls/xray-core:${XRAY_VER:-v26.3.27}
    container_name: xray-server
    restart: unless-stopped
    env_file:
      - .env
      - .env.secrets
    ports:
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./configs/server/config.json:/etc/xray/config.json:ro
